version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-ontainer
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_db:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.db
    env_file:
      - ./mysql/.env
